### PR TITLE
UI implemented

### PR DESCRIPTION
**Pull request by TMH1995**

### CODE REVIEW

**Comment by MaxGhenis** [comment]
@TMH1995 could you please fix the merge conflict?

**Comment by TMH1995** [comment]
> @TMH1995 could you please fix the merge conflict?

**Comment by TMH1995** [comment]
> @TMH1995 could you please fix the merge conflict?

I clicked on resolve conflict button and the conflict was disappeared.

**Comment by MaxGhenis** [comment]
@TMH1995 I think you clicked the close button instead? Could you reopen it and then we can take a look at the conflicts?

**Pull request closed without merging**
